pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: 'uday',
                    url: 'https://github.com/UdayKiranChilumula/Jenkins_pract.git',
                    branch: 'main'
            }
        }

        stage('Read JSON using Python') {
            steps {
                sh 'python3 /var/lib/jenkins/workspace/MT25010-Uday/Task-21-05-2025/task-5-json-reader/Task-21-04-2025/task-5/json_reader.py'
            }
        }
    }
}
